name: dockerCD

on:
    pull_request:
        types: [opened, reopened]
        branches:
        - develop
        - 'feature/**'


permissions:
    contents: write # for actions/checkout to fetch code
    issues: write

jobs:
    hadolint:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Docker linting using Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with: 
         failure-threshold: warning
      - name: Update Pull Request
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
            script: |
                const output = `
                #### Hadolint: \`${{ steps.hadolint.outcome }}\`
                \`\`\`
                ${process.env.HADOLINT_RESULTS}
                \`\`\`
                `;
        
                github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
                })
        
    build:
        runs-on: ubuntu-latest
        steps:
         - name: Checkout
           uses: actions/checkout@v4
         - name: Login to Docker Hub
           uses: docker/login-action@v3
           with:
             username: ${{ secrets.DOCKERHUB_USERNAME }}
             password: ${{ secrets.DOCKERHUB_TOKEN }}
         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v3
         - name: Build and push
           uses: docker/build-push-action@v5
           with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}