name: dockerCD

on:
    pull_request:
        types: [opened, reopened]
        branches:
        - develop
        - 'feature/**'


permissions:
    contents: read

jobs:
    hadolint:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Docker linting using Hadolint
        uses: hadolint/hadolint-action@77e79bb879e179a6f5f5a680d99d03589d77cd92
        
    build:
        runs-on: ubuntu-latest
        steps:
         - name: Checkout
           uses: actions/checkout@v4
         - name: Login to Docker Hub
           uses: docker/login-action@v3
           with:
             username: ${{ secrets.DOCKERHUB_USERNAME }}
             password: ${{ secrets.DOCKERHUB_TOKEN }}
         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v3
         - name: Build and push
           uses: docker/build-push-action@v5
           with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}